version: '3.8'

services:
  devcontainer:
    container_name: master-cs-module-1
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        PYTHON_VARIANT: 3.11-bullseye
        NODE_VERSION: "16"
        POETRY_VERSION: 1.1.14
    volumes:
      - ..:/workspace:cached
    init: true

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
