-- ------------------------------------------------------------------------------
--   DDL code by Andreas Ziegler - 2208771
--   2024-03-31
-- ------------------------------------------------------------------------------


-- Drop tables in reverse order of their creation due to foreign key constraints
DROP TABLE project_timetracking CASCADE CONSTRAINTS;
DROP TABLE department_managers CASCADE CONSTRAINTS;
DROP TABLE project_assignments CASCADE CONSTRAINTS;
DROP TABLE dependants CASCADE CONSTRAINTS;
DROP TABLE order_line_items CASCADE CONSTRAINTS;
DROP TABLE inventory CASCADE CONSTRAINTS;
DROP TABLE orders CASCADE CONSTRAINTS;
DROP TABLE customers CASCADE CONSTRAINTS;
DROP TABLE employees CASCADE CONSTRAINTS;
DROP TABLE projects CASCADE CONSTRAINTS;
DROP TABLE departments CASCADE CONSTRAINTS;
DROP TABLE locations CASCADE CONSTRAINTS;
DROP TABLE warehouses CASCADE CONSTRAINTS;
DROP TABLE products CASCADE CONSTRAINTS;

-- Create tables, starting with those that have no foreign keys
CREATE TABLE locations (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL
);

CREATE TABLE warehouses (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL
);

CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL
);

-- Create tables with dependencies
CREATE TABLE departments (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    location_id NUMBER NOT NULL,
    CONSTRAINT fk_location
        FOREIGN KEY (location_id) REFERENCES locations(id)
);

CREATE TABLE employees (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    department_id NUMBER NOT NULL,
    supervisor_id NUMBER,
    name VARCHAR2(255) NOT NULL,
    ssn VARCHAR2(255) NOT NULL,
    day_of_birth DATE,
    phone VARCHAR2(255),
    mobile VARCHAR2(255),
    email VARCHAR2(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    address VARCHAR2(255),
    salary NUMBER,
    CONSTRAINT fk_department_employees
        FOREIGN KEY (department_id) REFERENCES departments(id)
);

ALTER TABLE employees
    ADD CONSTRAINT fk_supervisor
        FOREIGN KEY (supervisor_id) REFERENCES employees(id);

CREATE TABLE customers (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    responsible_employee_id NUMBER NOT NULL,
    CONSTRAINT fk_responsible_employee
        FOREIGN KEY (responsible_employee_id) REFERENCES employees(id)
);

CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    CONSTRAINT fk_customer_orders
        FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE order_line_items (
    order_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    CONSTRAINT pk_order_line_items PRIMARY KEY (order_id, product_id),
    CONSTRAINT fk_order
        FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_product
        FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE department_managers (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    department_id NUMBER NOT NULL,
    employee_id NUMBER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    CONSTRAINT fk_department
        FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_employee
        FOREIGN KEY (employee_id) REFERENCES employees(id)
);

CREATE TABLE projects (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    responsible_department_id NUMBER,
    name VARCHAR2(255) NOT NULL,
    CONSTRAINT fk_department_projects
        FOREIGN KEY (responsible_department_id) REFERENCES departments(id)
);

CREATE TABLE project_assignments (
    project_id NUMBER NOT NULL,
    employee_id NUMBER NOT NULL,
    CONSTRAINT pk_project_assignments PRIMARY KEY (project_id, employee_id),
    CONSTRAINT fk_project
        FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_employee_project
        FOREIGN KEY (employee_id) REFERENCES employees(id)
);

CREATE TABLE project_timetracking (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    project_id NUMBER NOT NULL,
    employee_id NUMBER NOT NULL,
    week_number NUMBER NOT NULL,
    hours_worked NUMBER NOT NULL,
    CONSTRAINT fk_project_timetracking_project
        FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_project_timetracking_employee
        FOREIGN KEY (employee_id) REFERENCES employees(id)
);
-- only allow one time tracked per employee, project and week -> week numbers should look like 202401 which means first week in 2024
CREATE UNIQUE INDEX ui_project_employee_week ON project_timetracking(project_id, employee_id, week_number);

CREATE TABLE dependants (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,
    first_name VARCHAR2(255) NOT NULL,
    date_of_birth DATE NOT NULL,
    relationship VARCHAR2(255) NOT NULL,
    CONSTRAINT fk_employee_dependants
        FOREIGN KEY (employee_id) REFERENCES employees(id)
);

CREATE TABLE inventory (
    warehouse_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    stock NUMBER NOT NULL,
    CONSTRAINT pk_inventory PRIMARY KEY (warehouse_id, product_id),
    CONSTRAINT fk_warehouse
        FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_product_inventory
        FOREIGN KEY (product_id) REFERENCES products(id)
);
